"""Criação tabela Pagamentos, rotas e testes

Revision ID: 779920b0ff40
Revises: bc6efea2004e
Create Date: 2026-05-23 15:42:24.264533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779920b0ff40'
down_revision: Union[str, Sequence[str], None] = 'bc6efea2004e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamentos',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metodo', sa.String(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.pedido_id'], ),
    sa.PrimaryKeyConstraint('pedido_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    # ### end Alembic commands ###
