"""Criação tabela Item Pedido, rotas e testes

Revision ID: bf9bdf9f86a0
Revises: 779920b0ff40
Create Date: 2026-05-23 20:36:13.206712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9bdf9f86a0'
down_revision: Union[str, Sequence[str], None] = '779920b0ff40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_pedido',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.pedido_id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.produto_id'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'produto_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    # ### end Alembic commands ###
