"""criação da tabela pedidos

Revision ID: f5c9c43222a2
Revises: c1e475c92d72
Create Date: 2026-05-22 16:44:20.705532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c9c43222a2'
down_revision: Union[str, Sequence[str], None] = 'c1e475c92d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('canal_pedido', sa.String(), nullable=False),
    sa.Column('valor_pedido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('pedido_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    # ### end Alembic commands ###
